# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  serializer:
    serialize_null: true
  routing_loader: true
  allowed_methods_listener: true
  param_fetcher_listener: true
  view:
    view_response_listener: true
    formats:
      rss: false
      json: true
      xml: true
    force_redirects:
      html: true
    failed_validation: HTTP_UNPROCESSABLE_ENTITY
    empty_content: HTTP_NO_CONTENT
    default_engine: twig
  format_listener:
    rules:
      - { path: '^/$', priorities: [html], fallback_format: html, prefer_extension: true }
      - { path: '^/api-doc', priorities: [html], fallback_format: html, prefer_extension: true }
      - { path: '^/', priorities: [json, xml], fallback_format: json, prefer_extension: true }
