framework:
  secret: '%env(APP_SECRET)%'
  default_locale: '%locale%'
  csrf_protection: false
  http_method_override: true
  templating:
    engines: ['twig']
  serializer:
    enable_annotations: true
    name_converter: 'serializer.name_converter.camel_case_to_snake_case'
  php_errors:
    log: true
  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: ~
    cookie_secure: auto
    cookie_samesite: lax
