-- MySQL Script generated by MySQL Workbench
-- Sat Mar 16 17:38:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Technical identifier',
  `uuid` BINARY(16) NOT NULL COMMENT 'Functional identifier : UUID',
  `username` VARCHAR(255) NOT NULL COMMENT 'User login',
  `username_canonical` VARCHAR(255) NOT NULL COMMENT 'User canonical login',
  `email` VARCHAR(255) NOT NULL COMMENT 'User email',
  `email_canonical` VARCHAR(255) NOT NULL COMMENT 'User canonical email',
  `enabled` TINYINT(1) NOT NULL COMMENT 'Indicates if the user is active',
  `salt` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Password salt',
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL COMMENT 'User password',
  `last_login` DATETIME NULL DEFAULT NULL COMMENT 'User last login',
  `confirmation_token` VARCHAR(180) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Unused : confirmation token for password reset',
  `password_requested_at` DATETIME NULL DEFAULT NULL COMMENT 'Password request date',
  `roles` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT 'Unused : User roles',
  UNIQUE INDEX `uk_usr_username_canonical` (`username_canonical` ASC),
  UNIQUE INDEX `uk_usr_email_canonical` (`email_canonical` ASC),
  UNIQUE INDEX `uk_usr_confirmation_token` (`confirmation_token` ASC),
  UNIQUE INDEX `uk_usr_uuid` (`uuid` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `refresh_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refresh_tokens` ;

CREATE TABLE IF NOT EXISTS `refresh_tokens` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Technical identifier',
  `refresh_token` VARCHAR(128) NOT NULL COMMENT 'Refresh token code',
  `username` VARCHAR(255) NOT NULL COMMENT 'User associated (username)',
  `valid` DATETIME NOT NULL COMMENT 'Refresh token limit date',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_rtk_refresh_token` (`refresh_token` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
